services:
  seikatsudo_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - PASSWORD=samapi
    volumes:
      - ./src:/usr/src/app/src
  
  seikatsudo_db:
    image: mysql
    ports:
      - '3307:3307'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=seikatsudo
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser
      - MYSQL_TCP_PORT=3307
